### ISSUE TITLE
Formatting not PEP 8 Compliant

### ISSUE THREAD

**Issue by janothan** [mariaangelapellegrino/Evaluation-Framework#14]
The formatting is not compliant with [PEP 8](https://www.python.org/dev/peps/pep-0008/).
I _highly_ recommend to adhere to such standards.

The good news is that it is super simple to comply if you use some command line formatter such as [`black`](https://github.com/psf/black).

I can format the project for you but this would lead to a very lengthy commit. You need to use the same formatter for your dev branch otherwise will end up in a giant merge conflict.

My proposal: Use black and format `dev` and `master`. If you want me to re-format `master`, just confirm this in a comment (but be aware of merge conflicts when merging dev and not formatting dev before).

**Comment by mariaangelapellegrino** [comment]
Yes, go on in formatting the master, thanks.

**Comment by janothan** [comment]
This issue was resolved by commit 7e2de69.
